version: '2.1'
services:
  mongodb:
    container_name: test-mongodb
    image: mongo:6.0.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27019:27017'
