- name: DEPLOY FORUM APP
  hosts: localhost
  connection: local
  tasks:
  - name: PULL REPO
    shell: 'git clone https://github.com/mikebychkov/forum-mvc-app'

  - name: START TEST MONGO
    shell: 'cd ~/forum-mvc-app/ && docker-compose -f test-compose.yml up -d'

  - name: BUILD JAR WITH TESTS
    shell: 'cd ~/forum-mvc-app/ && ./mvnw package'

  # NEW IMAGE CREATION
  # DEPLOY TO K8S

  - name: STOP TEST MONGO
    shell: 'cd ~/forum-mvc-app/ && docker-compose -f test-compose.yml down'

  - name: CLEAN UP
    shell: 'rm -rf ~/forum-mvc-app/'
